### ISSUE TITLE
Indexes do not work

### ISSUE THREAD

**Issue by escoand** [premnirmal/StockTicker#10]
Indexes like ^GDAXI are found but they are not updated - maybe its because the are without the ^ in the portfolio

**Comment by escoand** [comment]
Search for DAX to reproduce the problem

**Comment by premnirmal** [comment]
Thanks for your feedback @escoand . I know indices don't work, it's because the yahoo finance api doesn't provide them. Google finance does however their api is deprecated so it causes some issues, I believe they enforce some limiting. The code for google finance is commented but you can enable it and use it, that will get the quotes for those indices
