### ISSUE TITLE
Enter current stock or price when bought

### ISSUE THREAD

**Issue by natrius** [premnirmal/StockTicker#190]
Probably a dumb question, but do i enter the price when i bought or really the current price. My guess is, when bought, so the difference gets shown but it somehow is not the same like online.

**Comment by Ikosihenagon** [comment]
That's the correct way to do it i think - at least it works like this for my stocks. Unfortunately, if the price has too many digits after the decimal, I have to round up to get a fitting value.

**Comment by ThomasWaldmann** [comment]
Also, one can not enter a currency unit when entering a price (e.g. if one buys in EUR [or has historic notes about buys in EUR]).

**Comment by natrius** [comment]
Okay, i worked it out.

Enter prices with the price you bought. Multiple stocks with different prices can be added. For @ThomasWaldmann : There are different markets. For Frankfurt, search there https://www.boerse-frankfurt.de/ for the ISIN. The symbol for Blackberry on https://www.finanzen.net/aktien/blackberry-aktie is `BB` - thats NYSE. On Frankfurt its https://www.boerse-frankfurt.de/equity/blackberry-ltd `RI1` - you will find it with `RI1` in StockTicker as well.

Hope that helps.

**Comment by ThomasWaldmann** [comment]
@natrius thanks for the hint!

i tried that with mixed results:

- for my arcimoto, tsmc and xiaomi stock, it worked, i could select it from frankfurt via ISIN and enter my amount and EUR purchase price, problem solved for these.

- for my AMD stock, it did not work, the ISIN is US0079031078, the symbol is "AMD" (frankfurt shows that) and it is in US dollar only, so the app miscomputes the gain if I enter my EUR purchase price (and I do not have a USD purchase price)

**Comment by natrius** [comment]
Tried AMD myself and i have no clue on what to do about that, sorry. If you work it out, let me know, in case i stumble upon this myself later on.

**Comment by premnirmal** [comment]
The app cannot convert from one currency to another, you need to enter the stock price in the same currency as the stock. Happy to take requests to enhance the code though

**Comment by ThomasWaldmann** [comment]
I guess the app can't solve this, except if you add buying timestamp, buying currency and you have access to historic (and current) currency conversion rates.

It's that complicated, because for such cases, we have 2 overlapping effects:
- first, change of currency exchange rate (imagine a stock in USD did not change its USD share value at all, but the USD is now twice as expensive in EUR as it was when you bought the stock - then the stock has doubled its value in EUR)
- second, usually stock value changes over time, so that is the other effect

Solution (this could be in the docs / help):
- assume the stock is valued in USD at the selected market (app shows USD) and your can't find a market that values it at the desired currency
- assume you bought the stock at date D in EUR
- find the historic conversion rate at date D for EUR to USD
- compute the per share USD value from the per share EUR price you paid at D
- enter that USD value in the app for your position
- the gains/losses will be correct now as all relevant values for that stock are in USD
- you have to live with value display in USD for that stock (which is **more or less acceptable**)
- I guess that the overall value of all investments will be **wrong** though, as it stupidly sums up values in different currencies?

**Comment by ThomasWaldmann** [comment]
An idea to solve this is to split the portfolio into 2 portfolies, e.g. EUR and USD based.

IIRC, there is another ticket about multi-portfolio, which could be used for this.

**Comment by natrius** [comment]
Added an explanation to the readme, merged now. Will close for now :)
