### ISSUE TITLE
Lost portfolio data after update

### ISSUE THREAD

**Issue by UnnamedGitHubUser** [premnirmal/StockTicker#229]
It looks like my app updated automatically overnight and I lost a large widget and portfolio that I had on my home screen. I cannot find a backup or way to restore what was approximately 40 stocks in my portfolio as well as holdings. Any suggestions as to how I can restore this quickly before it gets overwritten? The widget that was on my home screen is gone and when I go in the settings in the app there is a small portfolio that doesn't match my prior data.

**Comment by spmulders** [comment]
Same here, lost my complete portfolio and as a consequence the two widgets I had stopped working. Any idea for a fix?

**Comment by premnirmal** [comment]
I am not sure what has caused this bug, but it could be because the widget was renamed from `StockWidget` to `StocksWidgetProvider` (see https://github.com/premnirmal/StockTicker/commit/58aac59d5024bbc4a537d96e8ffdab3dc32be54e#diff-7fa6aef292187a049f7a4d6060d8df3ba212d838789c78940bd363344b1c38cdL108). I will rename it back to see if it fixes the issue

**Comment by dirk-de-bugger** [comment]
Had the same issue. Also the widget disappeared. But after some time not looking at it (been busy) my portfilio reappeared. Maybe force close helps?

**Comment by fastshow** [comment]
Same here, lost my entire portfolio and the widget just shows the placeholder StockWidget icon. If it helps diagnose the issue, mine seems to have reverted back to a portfolio I had about 10 or 12 months ago. Also, if I search for stocks I previously had in my portfolio, it shows the minus rather than plus icon, so somewhere internally it is still tracking what was in my list of stocks.

**Comment by premnirmal** [comment]
Attempted a fix in version 3.9.744: https://github.com/premnirmal/StockTicker/commit/11829cf47a150fc225244f27e140f665135c2654

**Comment by fastshow** [comment]
> Attempted a fix in version 3.9.744: [11829cf](https://github.com/premnirmal/StockTicker/commit/11829cf47a150fc225244f27e140f665135c2654)

That did it although it had brought back an old holding that wasn't present before the update. Also, now you've added last/next fetch at the top on 2-lines, it's made my previously non-scrolling 6-line widget require a scroll, any chance you can reduce the fetch times to a single line or give an option to toggle it off?

**Comment by wilx** [comment]
Is the .744 build supposed to return the lost portfolio? Because it did not fix it for me.

**Comment by wilx** [comment]
OK. The .745 version fixed it for me. My portfolio is back.
