### ISSUE TITLE
Fetch text

### ISSUE THREAD

**Issue by bradleap** [premnirmal/StockTicker#30]
How bout an option to remove the last and next fetch from widget since you added the refresh button? thanks

**Comment by premnirmal** [comment]
In terms of real estate, not sure if this is a a good idea to remove the last and next fetch: because if they are removed there will be empty space. That row will always be visible and empty because of the refresh button. This widget is aimed to make the most of the real estate available on the android home screen, so it would be a good idea to fill the space with something.

Any UI suggestions to fix that? Also, PRs are welcome :)

**Comment by premnirmal** [comment]
@bradleap please reopen if you have any more feedback
