### ISSUE TITLE
Allow user to add multiple widgets

### ISSUE THREAD

**Issue by premnirmal** [premnirmal/StockTicker#32]
And group stocks to different widgets

@Spqr753 tracking this issue here

**Comment by premnirmal** [comment]
@spqr753 this feature is available now in v2.3

**Comment by Spqr753** [comment]
Thank you, I am already using it!!!!!!  Great. 



-------- Original message --------From: Prem Nirmal <notifications@github.com> Date: 16/06/2017  15:15  (GMT+01:00) To: premnirmal/StockTicker <StockTicker@noreply.github.com> Cc: Spqr753 <Spqr753@yahoo.com>, Mention <mention@noreply.github.com> Subject: Re: [premnirmal/StockTicker] Allow user to add multiple widgets (#32) 
@Spqr753 this feature is available now in v2.3

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/premnirmal/StockTicker","title":"premnirmal/StockTicker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/premnirmal/StockTicker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@premnirmal in #32: @spqr753 this feature is available now in v2.3"}],"action":{"name":"View Issue","url":"https://github.com/premnirmal/StockTicker/issues/32#issuecomment-309023379"}}}
