### ISSUE TITLE
Provide ability to add multiple positions

### ISSUE THREAD

**Issue by webmihir** [premnirmal/StockTicker#38]
Currently I can edit a position for a given stock symbol. However, more often, people buy multiple lots/positions. For example, here is a typical purchase for me:

12/30/16: Bought 10 units of [ticker] at $900.01
1/17/17: Bought 8 units of [ticker] at $843.33

Currently, I can only add one position per ticker symbol. I would like to be able to add multiple positions.

**Comment by stefanvanegmond** [comment]
Hi I'm looking in to this. What I did it to add the option to added and subtract/remove shares to your position. It uses the average price to calculate gains and losses. It is also easy to extend the functionality and create a log of all position changes. I didn't create the GUI for it yet as I wanted to test the code as is. I'm unable to do so because I get unauthorized error when retrieving data from robindahood.com. How can I resolve that?

**Comment by premnirmal** [comment]
The API is private, so it will not be accessible by apps other than the production app. If you want to test you can mock the `RobindahoodaApi` class

**Comment by premnirmal** [comment]
This is a good feature to have, looking forward to seeing it

**Comment by stefanvanegmond** [comment]
Hi, 

Pull request is created . If users feel it is useful I can added a log for the position changes.

Kind Regards

Stefan
