### ISSUE TITLE
Feature request: Monitor portfolio

### ISSUE THREAD

**Issue by howeyc** [premnirmal/StockTicker#7]
Would it be possible to have the ability to specify share count and avg price (price owned) when adding a ticker?

That way on the main page you could show the gain/loss based on current price compared to owned price. Maybe in the place of 52 week hi/lo numbers?

I tried forking it and doing in myself but my Java skills are terrible. Also, does the Android studio have some kind of GUI to edit the layout files (similar to how you'd make a form in Visual Studio for example)?

If you don't have time or desire to do such a change I understand. I'll keep plugging along to see if I can do it.

**Comment by premnirmal** [comment]
Thanks for the feedback. That's a great suggestion, I'd be happy to help. If you can do it feel free to give me a pull request. I can get to it in about 2 weeks, my schedule is a little busy right now

**Comment by howeyc** [comment]
Okay great. I'll try and do it. Hopefully I can figure it out and have a pull request for you.


On June 23, 2015 8:59:25 PM CDT, Prem <notifications@github.com> wrote:
>Thanks for the feedback. That's a great suggestion, I'd be happy to
>help. If you can do it feel free to give me a pull request. I can get
>to it in about 2 weeks, my schedule is a little busy right now
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/premnirmal/StockTicker/issues/7#issuecomment-114697539

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by premnirmal** [comment]
Great. Android studio does have a GUI editor for xml layout files (under res/layout/ folder)

**Comment by howeyc** [comment]
I know I'm probably missing something stupid here, but I can't get this thing to build. Some kind of intermediate file it's generating.

I cloned this, opened it in Android Studio, and when I build it throws an Error about BuildConfig.java. This is what the file looks like that's it's generating:

```java
/**
 * Automatically generated file. DO NOT MODIFY
 */
package com.github.premnirmal.tickerwidget;

public final class BuildConfig {
  public static final boolean DEBUG = false;
  public static final String APPLICATION_ID = "com.github.premnirmal.tickerwidget";
  public static final String BUILD_TYPE = "release";
  public static final String FLAVOR = "prod";
  public static final int VERSION_CODE = 66;
  public static final String VERSION_NAME = "1.10.52";
  // Fields from default config.
  public static final String KEY = ;
}
```

They KEY is empty, but I have no idea where it's coming from.

**Comment by premnirmal** [comment]
Ah, that's the analytics key, which is in .gitignore, so when anybody from github builds it it populates the key with `""`, however there was a bug which didn't add the quotes because they weren't escaped.

Fixed now in this commit: https://github.com/premnirmal/StockTicker/commit/68184a62a6f9758af926fcf7c01a183f8e70d936

If you pull now and rebuild, it will run.

I never saw this bug because on my machine the analytics key file is present.
Thanks for pointing that out! Let me know if there's anything else I can do to help. The long weekend is coming up, I'll be able to jump onto this during the weekend. By that time if you have any changes we should coordinate and merge them, or we should at least piggy back those changes.

**Comment by howeyc** [comment]
Awesome! I like the changes you made too!

Thanks.
